#!/usr/bin/env bash
# A script to install nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
service nginx start
