#!/usr/bin/env bash
# A script to configure Nginx server so that /redirect_me is redirecting to another page.

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
				location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
				}
        error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /var/www/html/;
                internal;
        }
}
" > /etc/nginx/sites-available/default
service nginx restart
