#!/usr/bin/env bash
#A Bash script that loops from 1 to 10
i=1
while [ $i -lt 11 ]
do
	if [ $i = 4 ]
	then
		echo "bad luck"
	elif [ $i = 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	i=$((i+1))
done
